### ISSUE TITLE
Celery group tasks

### ISSUE THREAD

**Issue by Egnod** [kai3341/celery-pool-asyncio#22]
* Celery Executor version: 4.4.6
* Python version: 3.8
* Operating System: Ubuntu 19.10

### Description

Hi, I would like to ask how celery tasks group works and does it work? I tried to apply groups, but unfortunately, nothing worked. Sample code and errors are attached.

### What I Did

```
tasks = await group(tasks).delay()
```

```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/celery_pool_asyncio/tracer.py", line 197, in trace_task
R = retval = coro_task.result()
File "/back/core/tasks/tasks.py", line 40, in tasks
tasks = await group(tasks).delay()
TypeError: object GroupResult can't be used in 'await' expression
```

**Comment by kai3341** [comment]
Nice catch! I'll fix it soon

**Comment by kai3341** [comment]
#27
